apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atlantis
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: atlantis
      containers:
      - $setElementOrder/env:
        - name: ATLANTIS_REPO_WHITELIST
        - name: ATLANTIS_GH_APP_ID
        - name: ATLANTIS_GH_APP_KEY_FILE
        - name: ATLANTIS_GH_WEBHOOK_SECRET
        - name: ATLANTIS_WRITE_GIT_CREDS
        - name: ATLANTIS_DATA_DIR
        - name: ATLANTIS_PORT
        - name: ATLANTIS_ATLANTIS_URL
        env:
        - name: ATLANTIS_REPO_WHITELIST
          value: github.com/org/repo # Update me
        - name: ATLANTIS_GH_APP_ID
          value: "12345" # Update me after GitHub app is created
        - name: ATLANTIS_ATLANTIS_URL
          value: https://atlantis-test.example.com # Update me
        image: runatlantis/atlantis:v0.15.0 # Update me
        name: atlantis
