apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atlantis
spec:
  template:
    spec:
      containers:
      - env:
        - name: ATLANTIS_REPO_ALLOWLIST
          value: github.com/org/repo # Update me
        - name: ATLANTIS_GH_APP_ID
          value: "12345" # Update me after GitHub app is created
        - name: ATLANTIS_ATLANTIS_URL
          value: https://atlantis-test.example.com # Update me
        image: runatlantis/atlantis:v0.18.2 # Update to latest
        name: atlantis
