apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: atlantis
  name: atlantis
spec:
  template:
    spec:
      containers:
      - env:
        - name: ATLANTIS_REPO_ALLOWLIST
          value: github.com/org/repo # Update me
        - name: ATLANTIS_ATLANTIS_URL
          value: https://atlantis-test.example.com # Update me
        image: runatlantis/atlantis:v0.18.2 # Update to latest
        name: atlantis
