apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- https://github.com/statisticsnorway/atlantis-bootstrap/kubernetes-manifests/runfirst?ref=v3.0.0
patchesStrategicMerge:
- ingress.yaml
- atlantis-runfirst.yaml
