apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certificate
  namespace: default
spec:
  secretName: atlantis-ingress-certs
  commonName: 'atlantis-test.example.com'
  issuerRef:
    name: letsencrypt
    kind: Issuer
  dnsNames:
  - atlantis-test.example.com
